name: client_web_cliente_cms_projeto
description: "A new Flutter project."
publish_to: 'none' 
version: 0.0.1-3
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in_web: ^0.12.4

  #Dependencias internas
  dependencies:
    path: ../../modules/dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
