name: dependencies
description: "Modulo responsável pelo gerenciamento das dependencias."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter
  return_success_or_error: ^0.18.0
  android_power_manager: ^1.0.0
  permission_handler: ^11.3.1
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.2
  connectivity_plus: ^6.0.3
  get: ^4.6.6
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.3
  cloud_firestore: ^4.17.1
  firebase_remote_config: ^4.3.14
  firebase_auth: ^4.19.3
  google_sign_in: ^6.2.1
  device_info_plus: ^10.1.0
  uuid: ^4.4.0
  font_awesome_flutter: ^10.7.0
  logger: ^2.2.0

  #modulos
  services:
    path: ../services
  auth:
    path: ../auth
  core:
    path: ../core
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
